#!/env/bash

# This will grab all the modified, untracked, and deleted files
# that has been staged for commit, so the script doesn't run on any commit
MODIFIED_FILES=$(git diff --cached --name-status | awk '{print $2}') 
DOC_GENERATOR_REPO=kastle-lab/documentation-generator
OUTPUT_DIR="../documentation" # Change if output directory is different

get_pattern_files() {
	pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
	echo "$MODIFIED_FILES" | { grep "$pattern$" || true; }
}

get_documentation_generator() {
	# wget the script itself
	python -m wget "https://raw.githubusercontent.com/$DOC_GENERATOR_REPO/master/documentation-generator/documentation-generator.py"
}

install_dependencies() {
	python -m pip install rdflib wget
}

cleanup_and_exit() {
	# rm -rf documentation-generator # Uncomment if the entire repo is being cloned
	rm documentation-generator.py

	exit 1
}

# This will act as our filter to check if any of the owl files
# is part of the modified or untracked files
OWL_FILES=$(get_pattern_files .owl)

if [[ -n "$OWL_FILES" ]]; then
	cd modl

	# Check if the os is Windows
	# Because Python for Windows is added weirdly on PATH
	# if it is, use the `python` command
	if [[ "$OSTYPE" == "msys" ]] ; then
		if [[ $(python --version) != "Python 3"* ]] ; then
			echo "Python not found cannot initiate pre-commit"
			exit 1
		fi
	
	# If it's not, use python3
	elif [[ $(python3 --version) != "Python 3"* ]] ; then
		echo "Python not found cannot initiate pre-commit"
		exit 1
	fi

	install_dependencies

	get_documentation_generator

	# Go into the directory and execute the script
	python documentation-generator.py ./ $OUTPUT_DIR && echo "Successfully created documentations" || cleanup_and_exit

	# rm -rf documentation-generator # Uncomment if the entire repo is being cloned
	rm documentation-generator.py
	
	cd ..

else 
	echo "No changes done to owl file found, skipping pre-commit"
	exit 0
fi

# Add the new files to the commit
git add $OWL_FILES

# Exit with code 0 which will continue the commit
exit 0